### ISSUE TITLE
Children Objects Azimuths change after export/import

### ISSUE THREAD

**Issue by oliviervilledieu** [DorisSupport/NI_Twin#4]
When creating 'complex' objects by associating several objects, it appears that some children objects change azimuth after exporting and re-importing.

**Comment by DorisSupport** [comment]
Could you be more specific? and also provide the exported JSON file if possible? explaining what is expected and what is the actual result?
Thanks!

David

**Comment by oliviervilledieu** [comment]
Hello,

Sure can.
I created those suction piles with cross top structures by declaring cylinders as parent object for the two cross beams at the top
One of the beams azimuth I set to 90 deg.
'See snap 1' 
![snap 1](https://github.com/DorisSupport/NI_Twin/assets/173369644/22d81424-f957-42ad-acba-c29cba9c557b)

Then I export the project.

When I import again, the 90 deg beams have automatically changed to different values (15.5 deg).
Tried several times but always get the same result.
'see snap 2'
![snap 2](https://github.com/DorisSupport/NI_Twin/assets/173369644/407e1c01-d165-4282-a542-5e7f0c1d765e)

Json file attached.
[saved_project (11).json](https://github.com/user-attachments/files/15914098/saved_project.11.json)


Thanks!

**Comment by DorisSupport** [comment]
The bug is now corrected. The rotation of the child object was not saved properly when entered manually in the input field, then hitting enter to apply the modification, and finally hitting the "save" button.
Attached the corrected Project file, with 90° angles.
[saved_project.11_modified.json](https://github.com/user-attachments/files/15914922/saved_project.11_modified.json)

**Comment by oliviervilledieu** [comment]
Ok thank you
