### ISSUE TITLE
Issue when opening/importing saved project

### ISSUE THREAD

**Issue by mdenadai06** [DorisSupport/NI_Twin#8]
**Describe the bug**
When reopening project, Objects are appearing in very small dimensions compare to the ones set. 
Objects properties are still the good ones

**Comment by mdenadai06** [comment]
no comment

**Comment by DorisSupport** [comment]
Could you provide the Project file (load the project and then export as a local json file, and attach it here), or give me your email and the name/reference of the project you want to load so that I can go and check the saved data? Thanks!

**Comment by mdenadai06** [comment]
Thanks for your help,
See attached, files

Best regards
Mathieu

**Comment by DorisSupport** [comment]
Did not get the files here, but David sent them to me just before.
The bug is corrected. Attached the two files (I removed some "strange" additionnal piles that were packed out of the upper deck...)
[KASKIDA pile 5.5m dia - 5piles.json](https://github.com/user-attachments/files/17061329/KASKIDA.pile.5.5m.dia.-.5piles.json)
[Kaskida Pile -215t Max.json](https://github.com/user-attachments/files/17061330/Kaskida.Pile.-215t.Max.json)
